name: Application tests

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install depdendencies with yarn
        run: yarn --frozen-lockfile
      - name: Run jest tests
        run: yarn test
      
